/*
 Generated by typeshare 1.6.0
*/

export interface DataExplorerDataframe {
	columns: Array<Map<string, any>>;
	data: Array<Map<string, any>>;
}

export interface MuiTableColumns {
	accessorKey: string;
	header: string;
}

export interface S3Bucket {
	endpoint: string;
	bucket: string;
	access_key: string;
	secret_key: string;
}

export interface S3File {
	key: string;
}

